### ISSUE TITLE
v0.3.0 causing crash on Android

### ISSUE THREAD

**Issue by nemoryoliver** [kiwi-bop/flutter_crashlytics#71] opened 2019-03-22 02:52 UTC
The crash only happens when you run the app in Release Mode. A user has reported this log https://del.dog/zataziliwi but I am not 100% sure if it's related to this package. I've also tried running **flutter run --release --verbose** and I don't see any issue related to crashlytics

## Flutter Doctor

`[✓] Flutter (Channel master, v1.3.14-pre.7, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.3.14-pre.7 at /Users/nemory/Development/flutter
    • Framework revision ee3e621f02 (3 days ago), 2019-03-18 21:40:21 -0700
    • Engine revision 5088735e5f
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 None)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/nemory/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • BBF100 2 • 5000013362 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!`

**Comment by jaumard** [comment] 2019-03-22 10:18
Hi ! Your log look more like you're running the app on a non supported architecture of flutter as it doesn't find flutter.so. at least that's my guess ^^

**Comment by nemoryoliver** [comment] 2019-03-23 05:50
> Hi ! Your log look more like you're running the app on a non supported architecture of flutter as it doesn't find flutter.so. at least that's my guess ^^

Yeah.. but using v0.3.0 it crashes for me without any logs at all...

**Comment by jaumard** [comment] 2019-03-23 07:02
You'll not have crash report if it crash before you had the chance to start the app, which is the case here :/ crash report is enabled once you call `initialized` here it doesn't found the flutter binary so no change you'll get the crash

**Comment by dspoonia7** [comment] 2019-03-25 07:16
Facing the same issue. Android app is crashing in release mode. The app crashes even before opening. In debug mode it is working fine.

**Comment by edgartrem** [comment] 2019-03-26 05:02
The issue is because by default, flutter only includes the 32bit flutter engine _(armeabi-v7a)_ that means that only the _(armeabi-v7a)_ folder will exists inside your release apk. 64bit phones can run 32bit apps with no problem. 

The problem with version `v0.3.0` is that it now includes it's own binaries in order to also catch flutter engine crashes. This however introduces the _(arm64-v8a)_ folder into your app, 64bit phone will now target this folder, but there is no flutter engine in there as you can see. 

![Screen Shot 2562-03-26 at 11 40 57](https://user-images.githubusercontent.com/40788219/54972155-dbb48e80-4fbc-11e9-9d24-ebcc05b8b8a2.png)

You can find several solutions:

**Comment by jaumard** [comment] 2019-03-26 09:42
Ho nice finding @edgartrem ! I admit that I never deal with that, if anyone know how to fix this for I'll have to dig more.

**Comment by jaumard** [comment] 2019-03-27 17:53
Hey guys, I'm trying to find the root cause of this, do you mind trying this branch https://github.com/kiwi-bop/flutter_crashlytics/tree/bugfix/androidCrash I removed the NDK support as I'm guessing that's what causing the issue here. Let me know !

**Comment by slightfoot** [comment] 2019-03-28 12:02
Relates to flutter/flutter#18494

**Comment by jaumard** [comment] 2019-03-28 12:06
I'm closing this as it's not related to this package but to the issue linked by @edgartrem and @slightfoot :) thanks guys !

**Closed by jaumard** 2019-03-28 12:06 UTC
Labels: bug, help wanted
