### ISSUE TITLE
It is asking for Fabric in Firebase Crashlytics.

### ISSUE THREAD

**Issue by arnold-parge** [kiwi-bop/flutter_crashlytics#52] opened 2019-01-23 07:29 UTC
I get exception when setup this plugin:

```
This app relies on Crashlytics. Please sign up for access at https://fabric.io/sign_up,
install an Android build tool and ask a team member to invite you to this app's organization.
```
I am using only Firebase Crashlytics and not Fabric. Am I supposed to use both, I guess not.

**Steps I followed.**
- Create android app on firebase
- Save `google-services.json` file in `app` folder.
- Install plugin
- Change `main()` to below snippet

```
void main() async {
  bool isInDebugMode = false;

  FlutterError.onError = (FlutterErrorDetails details) {
    if (isInDebugMode) {
      // In development mode simply print to console.
      FlutterError.dumpErrorToConsole(details);
    } else {
      // In production mode report to the application zone to report to
      // Crashlytics.
      Zone.current.handleUncaughtError(details.exception, details.stack);
    }
  };

  await FlutterCrashlytics().initialize();

  runZoned<Future<Null>>(() async {
    runApp(MyApp());
  }, onError: (error, stackTrace) async {
    // Whenever an error occurs, call the `reportCrash` function. This will send
    // Dart errors to our dev console or Crashlytics depending on the environment.
    await FlutterCrashlytics()
        .reportCrash(error, stackTrace, forceCrash: false);
  });
}
```

**Logs:**
```
Launching lib/main.dart on Lenovo K33a42 in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Built build/app/outputs/apk/debug/app-debug.apk.
I/OpenGLRenderer(30155): Initialized EGL, version 1.4
D/OpenGLRenderer(30155): Swap behavior 1
I/Choreographer(30155): Skipped 34 frames!  The application may be doing too much work on its main thread.
E/CrashlyticsCore(30155): .
E/CrashlyticsCore(30155): .     |  |
E/CrashlyticsCore(30155): .     |  |
E/CrashlyticsCore(30155): .     |  |
E/CrashlyticsCore(30155): .   \ |  | /
E/CrashlyticsCore(30155): .    \    /
E/CrashlyticsCore(30155): .     \  /
E/CrashlyticsCore(30155): .      \/
E/CrashlyticsCore(30155): .
E/CrashlyticsCore(30155): This app relies on Crashlytics. Please sign up for access at https://fabric.io/sign_up,
E/CrashlyticsCore(30155): install an Android build tool and ask a team member to invite you to this app's organization.
E/CrashlyticsCore(30155): .
E/CrashlyticsCore(30155): .      /\
E/CrashlyticsCore(30155): .     /  \
E/CrashlyticsCore(30155): .    /    \
E/CrashlyticsCore(30155): .   / |  | \
E/CrashlyticsCore(30155): .     |  |
E/CrashlyticsCore(30155): .     |  |
E/CrashlyticsCore(30155): .     |  |
E/CrashlyticsCore(30155): .
E/MethodChannel#flutter_crashlytics(30155): Failed to handle method call
E/MethodChannel#flutter_crashlytics(30155): io.fabric.sdk.android.services.concurrency.UnmetDependencyException: This app relies on Crashlytics. Please sign up for access at https://fabric.io/sign_up,
E/MethodChannel#flutter_crashlytics(30155): install an Android build tool and ask a team member to invite you to this app's organization.
E/MethodChannel#flutter_crashlytics(30155): 	at com.crashlytics.android.core.CrashlyticsCore.onPreExecute(CrashlyticsCore.java:241)
E/MethodChannel#flutter_crashlytics(30155): 	at com.crashlytics.android.core.CrashlyticsCore.onPreExecute(CrashlyticsCore.java:209)
E/MethodChannel#flutter_crashlytics(30155): 	at io.fabric.sdk.android.InitializationTask.onPreExecute(InitializationTask.java:44)
E/MethodChannel#flutter_crashlytics(30155): 	at io.fabric.sdk.android.services.concurrency.AsyncTask.executeOnExecutor(AsyncTask.java:611)
E/MethodChannel#flutter_crashlytics(30155): 	at io.fabric.sdk.android.services.concurrency.PriorityAsyncTask.executeOnExecutor(PriorityAsyncTask.java:43)
E/MethodChannel#flutter_crashlytics(30155): 	at io.fabric.sdk.android.Kit.initialize(Kit.java:69)
E/MethodChannel#flutter_crashlytics(30155): 	at io.fabric.sdk.android.Fabric.initializeKits(Fabric.java:466)
E/MethodChannel#flutter_crashlytics(30155): 	at io.fabric.sdk.android.Fabric.init(Fabric.java:410)
E/MethodChannel#flutter_crashlytics(30155): 	at io.fabric.sdk.android.Fabric.setFabric(Fabric.java:368)
E/MethodChannel#flutter_crashlytics(30155): 	at io.fabric.sdk.android.Fabric.with(Fabric.java:339)
E/MethodChannel#flutter_crashlytics(30155): 	at com.kiwi.fluttercrashlytics.FlutterCrashlyticsPlugin.onMethodCall(FlutterCrashlyticsPlugin.kt:27)
E/MethodChannel#flutter_crashlytics(30155): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#flutter_crashlytics(30155): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#flutter_crashlytics(30155): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_crashlytics(30155): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#flutter_crashlytics(30155): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#flutter_crashlytics(30155): 	at android.app.ActivityThread.main(ActivityThread.java:6077)
E/MethodChannel#flutter_crashlytics(30155): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_crashlytics(30155): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
E/MethodChannel#flutter_crashlytics(30155): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
D/NetworkSecurityConfig(30155): No Network Security Config specified, using platform default
I/DpmTcmClient(30155): RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
W/Fabric  (30155): Could not call getId on com.google.android.gms.ads.identifier.AdvertisingIdClient$Info
W/Fabric  (30155): Could not call isLimitAdTrackingEnabled on com.google.android.gms.ads.identifier.AdvertisingIdClient$Info
```

Flutter Doctor:
```
[✓] Flutter (Channel beta, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /home/arnold/installed/flutter
    • Framework revision 5391447fae (8 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/arnold/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/arnold/installed/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    ✗ Android license status unknown.

[✓] Android Studio (version 3.0)
    • Android Studio at /home/arnold/installed/android-studio
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Connected device (1 available)
    • Lenovo K33a42 • 192.168.0.6:5555 • android-arm • Android 7.0 (API 24)
```

**Comment by nemoryoliver** [comment] 2019-01-28 12:14
I got the same issue too.. @dhargitai do we only have to add the firebase pod or also the fabric pod?

**Comment by mathieujobin** [comment] 2019-02-10 08:32
worked for me ! thank you

**Comment by nemoryoliver** [comment] 2019-02-14 06:46
> worked for me ! thank you

which fix worked for you?

**Comment by iamnotaturtle** [comment] 2019-02-22 04:26
@nemoryoliver adding the fabric.io repo, adding the fabric plugin in the main `build.gradle` and applying the plugin in the `app/build.gradle` worked for me. I can see the dashboard initialized without needing a fabric.io account.

Basically the last steps from here: https://github.com/kiwi-bop/flutter_crashlytics#android

**Comment by diemer** [comment] 2019-02-25 18:13
@nemoryoliver the steps @iamnotaturtle said worked for me as well. I think the confusion is the way the setup instructions read: The API key part is the optional part, the part after it is not.

**Comment by saladthieves** [comment] 2019-02-26 17:02
@dhargitai thanks for the awesome fix! 
@diemer I'm considering sending a pull request with updated instructions and clearer implementation guidelines / goals to make future people's lives easier.

**Comment by nemoryoliver** [comment] 2019-02-26 23:33
Mine's working great now too as well. Just added some fabric requirements without api key. Thanks a lot all!

**Comment by kw2019ltd** [comment] 2019-03-01 18:49
firebase dashboard dose not show any error  , error being sent but i dont see it in firebase consol,

if i adding the fabirc aoi key its showing in fabric,  but if i remove it and trying only with firebase no error in dashboard

E/AndroidRuntime(15749): Caused by: com.kiwi.fluttercrashlytics.FlutterException: asssssssssssssss
E/AndroidRuntime(15749): 	at DrawerWidget._buildAppInfoListTile.<fn>(package:plants_price_flutter_app/widget/drawer/drawer_widget.dart:56)
E/AndroidRuntime(15749): 	at _InkResponseState._handleTap(package:flutter/src/material/ink_well.dart:513)
E/AndroidRuntime(15749): 	at _InkResponseState.build.<fn>(package:flutter/src/material/ink_well.dart:568)
E/AndroidRuntime(15749): 	at GestureRecognizer.invokeCallback(package:flutter/src/gestures/recognizer.dart:120)

**Comment by congdanh1608** [comment] 2019-03-05 08:39
> @nemoryoliver adding the fabric.io repo, adding the fabric plugin in the main `build.gradle` and applying the plugin in the `app/build.gradle` worked for me. I can see the dashboard initialized without needing a fabric.io account.
> 
> Basically the last steps from here: https://github.com/kiwi-bop/flutter_crashlytics#android

Hi, How can you add the apply fabric.io
I get this error when I try to add into gradle:

> Failed to apply plugin [id 'io.fabric']
   > Crashlytics was applied to a project without an Android plugin. Please make sure the Crashlytics plugin is applied after the appropriate Android plugin for your project.

**Comment by congdanh1608** [comment] 2019-03-05 08:53
> fabric requirements

Can you share it to me? What is fabric requirements which you added? Thanks

**Comment by congdanh1608** [comment] 2019-03-05 09:16
I solved it by this way:

1. Add this into project gradle
`buildscript {
  repositories {
...
    maven { url 'https://maven.fabric.io/public' }
  }

  dependencies {
...
    classpath 'io.fabric.tools:gradle:1.+'
  }
}`

2. Add this into app gradle:
after "apply plugin: 'com.android.application'"
`apply plugin: 'io.fabric'

repositories {
  maven { url 'https://maven.fabric.io/public' }
}`

into "dependencies"

`dependencies {
   ...
    implementation 'com.google.firebase:firebase-core:16.0.7'
    implementation('com.crashlytics.sdk.android:crashlytics:2.9.9@aar') {
        transitive = true;
    }
}`

and final:
`
apply plugin: 'com.google.gms.google-services'`

**Comment by jaumard** [comment] 2019-03-28 12:27
I'm closing this as it's a configuration issue and fixes has been provided, thanks guys

**Closed by jaumard** 2019-03-28 12:27 UTC
